import type { NextPage } from 'next'
import Head from 'next/head'
import LoadImage from '../../components/Image';
import styles from '../../styles/Home.module.css';
import { styled } from '@mui/material/styles';
import Grid from '@mui/material/Grid';
import Paper from "@mui/material/Paper";
import Product from '../../components/Product';
import Loader from '../../components/Loader';

const Item = styled(Paper)(({ theme }) => ({

    width: 200,
    height: 300,
    padding: theme.spacing(5),
    textAlign: 'center',
    color: theme.palette.text.secondary,
}));

const Home: NextPage = () => {
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.m2}>
                <h1>Test successful</h1>
                <Loader></Loader>
                <Grid container my={2}>
                    <Grid lg={8}>
                        <Product imageName="phone.jpg">
                            Hello
                        </Product>
                    </Grid>
                    <Grid item={true} lg={4}>
                        right pael
                    </Grid>
                </Grid>
            </main>
        </div>
    )
}

export default Home
